CREATE TABLE IF NOT EXISTS users (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(45) NOT NULL,
pw VARCHAR(45) NOT NULL,
active INT NOT NULL
);

CREATE TABLE IF NOT EXISTS permissions (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(45) NOT NULL,
privilege VARCHAR(45) NOT NULL
);